### ISSUE TITLE
Game Not Loading 

### ISSUE THREAD

**Issue by Cibsmart** [BlueMagnificent/baller#1]
After running ``` npm start ```, the Desktop browser opens and Game starts loading but never loads. See attachement.

![capture](https://user-images.githubusercontent.com/12666230/52200234-808dd780-2868-11e9-9874-f13385f71b52.PNG)

**Comment by BlueMagnificent** [comment]
This was caused by wrongly importing GLTFLoader.js with import loader. This has been corrected
